# .github/workflows/ml-ci-cd.yml
name: ML CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PORT: 8080

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Include necessary Python packages

      - name: Data Generation
        run: python generate_data.py

      - name: Data Preprocessing
        run: python preprocessing.py

      - name: Model Training
        run: python train.py

      - name: Data Test Generation
        run: python generate_test_data.py

      - name: Model Testing
        run: python test.py

      - name: Model Deployment
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          pip install python-dotenv
          python -c "from dotenv import dotenv_values; import os; os.environ.update(dotenv_values('.env'))"            
          echo $PORT
          python -m flask run --port $PORT
